name: Generate Snake Animation

on:
  # Chạy mỗi ngày lúc 5h sáng (UTC) hoặc khi push lên main
  schedule:
    - cron: "0 5 * * *"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Generate GitHub Contribution Grid Snake Animation
        uses: Platane/snk@v3
        with:
          github_user_name: nguyenhoangtuantu
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      - name: Push changes
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
